# name: Reset Leaderboard

# on:
#   schedule:
#     # Runs every day at 12:00 AM UTC
#     - cron: '0 0 * * *'
#   workflow_dispatch:   # allows manual trigger from GitHub Actions tab

# jobs:
#   call-api:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Call Reset Leaderboard API
#         run: |
#           curl --fail -X GET "https://author.edulips.com/reset-leaderboard"
