name: Reset Leaderboard

on:
  schedule:
    # Runs every day at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      # Use a simple curl command to hit the endpoint
      - name: Call Reset Leaderboard API
        run: |
          curl -X GET https://author.edulips.com/reset-leaderboard