name: Trigger News Data Rearrange

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 30 minutes

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Vercel API
      run: |
        curl -X GET https://author.edulips.com/rearrange
